In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf

# Import our input dataset
attrition_df = pd.read_csv('HR-Employee-Attrition.csv')
attrition_df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [2]:
# Generate our categorical variable list
attrition_cat = attrition_df.dtypes[attrition_df.dtypes == "object"].index.tolist()

In [3]:
# Check the number of unique values in each column
attrition_df[attrition_cat].nunique()

Attrition         2
BusinessTravel    3
Department        3
EducationField    6
Gender            2
JobRole           9
MaritalStatus     3
Over18            1
OverTime          2
dtype: int64

In [4]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(attrition_df[attrition_cat]))

# Add the encoded variable names to the DataFrame
encode_df.columns = enc.get_feature_names(attrition_cat)
encode_df.head()

,Attrition_No,Attrition_Yes,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [5]:
# Merge one-hot encoded features and drop the originals
attrition_df = attrition_df.merge(encode_df,left_index=True, right_index=True)
attrition_df = attrition_df.drop(attrition_cat,1)
attrition_df.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,49,279,8,1,1,2,3,61,2,2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,37,1373,2,2,1,4,4,92,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,33,1392,3,4,1,5,4,56,3,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,27,591,2,1,1,7,1,40,3,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [6]:
# Split our preprocessed data into our features and target arrays
y = attrition_df["Attrition_Yes"].values
X = attrition_df.drop(["Attrition_Yes","Attrition_No"],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [7]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [8]:
# Define the model - deep neural net
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  8
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 8)                 448
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 45
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 6
=================================================================
Total params: 499
Trainable params: 499
Non-trainable params: 0
_________________________________________________________________

In [9]:
# Import checkpoint dependencies
import os
from tensorflow.keras.callbacks import ModelCheckpoint

# Define the checkpoint path and filenames
os.makedirs("checkpoints/",exist_ok=True)
checkpoint_path = "checkpoints/weights.{epoch:02d}.hdf5"

In [11]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Create a callback that saves the model's weights every 5 epochs
cp_callback = ModelCheckpoint(
    filepath=checkpoint_path,
    verbose=1,
    save_weights_only=True,
    save_freq=1000)

# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100,callbacks=[cp_callback])

# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/100
35/35 [==============================] - 0s 841us/step - loss: 0.7738 - accuracy: 0.4171
Epoch 2/100
35/35 [==============================] - 0s 812us/step - loss: 0.6923 - accuracy: 0.5792
Epoch 3/100
35/35 [==============================] - 0s 849us/step - loss: 0.6384 - accuracy: 0.7207
Epoch 4/100
35/35 [==============================] - 0s 849us/step - loss: 0.5766 - accuracy: 0.8051
Epoch 5/100
35/35 [==============================] - 0s 861us/step - loss: 0.5415 - accuracy: 0.8120
Epoch 6/100
35/35 [==============================] - 0s 869us/step - loss: 0.4808 - accuracy: 0.8488
Epoch 7/100
35/35 [==============================] - 0s 871us/step - loss: 0.4481 - accuracy: 0.8455
Epoch 8/100
35/35 [==============================] - 0s 882us/step - loss: 0.4193 - accuracy: 0.8557
Epoch 9/100
35/35 [==============================] - 0s 876us/step - loss: 0.3929 - accuracy: 0.8612
Epoch 10/100
35/35 [==============================] - 0s 902us/step - loss: 0.3738 - accuracy: 0.8596
Epoch 11/100
35/35 [==============================] - 0s 878us/step - loss: 0.3594 - accuracy: 0.8690
Epoch 12/100
35/35 [==============================] - 0s 882us/step - loss: 0.3494 - accuracy: 0.8824
Epoch 13/100
35/35 [==============================] - 0s 900us/step - loss: 0.3058 - accuracy: 0.8828
Epoch 14/100
35/35 [==============================] - 0s 907us/step - loss: 0.3332 - accuracy: 0.8867
Epoch 15/100
35/35 [==============================] - 0s 905us/step - loss: 0.3463 - accuracy: 0.8725
Epoch 16/100
35/35 [==============================] - 0s 902us/step - loss: 0.3226 - accuracy: 0.8830
Epoch 17/100
35/35 [==============================] - 0s 880us/step - loss: 0.2957 - accuracy: 0.8995
Epoch 18/100
35/35 [==============================] - 0s 898us/step - loss: 0.2924 - accuracy: 0.8954
Epoch 19/100
35/35 [==============================] - 0s 907us/step - loss: 0.2775 - accuracy: 0.9031
Epoch 20/100
35/35 [==============================] - 0s 868us/step - loss: 0.2742 - accuracy: 0.9092
Epoch 21/100
35/35 [==============================] - 0s 902us/step - loss: 0.2962 - accuracy: 0.9022
Epoch 22/100
35/35 [==============================] - 0s 862us/step - loss: 0.2830 - accuracy: 0.9008
Epoch 23/100
35/35 [==============================] - 0s 894us/step - loss: 0.2669 - accuracy: 0.9081
Epoch 24/100
35/35 [==============================] - 0s 908us/step - loss: 0.2638 - accuracy: 0.9062
Epoch 25/100
35/35 [==============================] - 0s 917us/step - loss: 0.2425 - accuracy: 0.9124
Epoch 26/100
35/35 [==============================] - 0s 898us/step - loss: 0.2550 - accuracy: 0.9021
Epoch 27/100
35/35 [==============================] - 0s 874us/step - loss: 0.2649 - accuracy: 0.8996
Epoch 28/100
35/35 [==============================] - 0s 887us/step - loss: 0.2512 - accuracy: 0.9103
Epoch 29/100
 1/35 [..............................] - ETA: 0s - loss: 0.2759 - accuracy: 0.8750
Epoch 00029: saving model to checkpoints/weights.29.hdf5
35/35 [==============================] - 0s 1ms/step - loss: 0.2536 - accuracy: 0.9010
Epoch 30/100
35/35 [==============================] - 0s 883us/step - loss: 0.2314 - accuracy: 0.9138
Epoch 31/100
35/35 [==============================] - 0s 904us/step - loss: 0.2274 - accuracy: 0.9203
Epoch 32/100
35/35 [==============================] - 0s 876us/step - loss: 0.2523 - accuracy: 0.8992
Epoch 33/100
35/35 [==============================] - 0s 911us/step - loss: 0.2278 - accuracy: 0.9048
Epoch 34/100
35/35 [==============================] - 0s 939us/step - loss: 0.2409 - accuracy: 0.9050
Epoch 35/100
35/35 [==============================] - 0s 935us/step - loss: 0.2277 - accuracy: 0.9114
Epoch 36/100
35/35 [==============================] - 0s 968us/step - loss: 0.2313 - accuracy: 0.9069
Epoch 37/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2313 - accuracy: 0.9102
Epoch 38/100
35/35 [==============================] - 0s 840us/step - loss: 0.2324 - accuracy: 0.9073
Epoch 39/100
35/35 [==============================] - 0s 880us/step - loss: 0.2339 - accuracy: 0.9092
Epoch 40/100
35/35 [==============================] - 0s 964us/step - loss: 0.2172 - accuracy: 0.9107
Epoch 41/100
35/35 [==============================] - 0s 999us/step - loss: 0.2368 - accuracy: 0.9029
Epoch 42/100
35/35 [==============================] - 0s 887us/step - loss: 0.2037 - accuracy: 0.9121
Epoch 43/100
35/35 [==============================] - 0s 948us/step - loss: 0.2061 - accuracy: 0.9191
Epoch 44/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2137 - accuracy: 0.9171
Epoch 45/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2179 - accuracy: 0.9194
Epoch 46/100
35/35 [==============================] - 0s 863us/step - loss: 0.2084 - accuracy: 0.9181
Epoch 47/100
35/35 [==============================] - 0s 859us/step - loss: 0.2067 - accuracy: 0.9148
Epoch 48/100
35/35 [==============================] - 0s 849us/step - loss: 0.2074 - accuracy: 0.9195
Epoch 49/100
35/35 [==============================] - 0s 875us/step - loss: 0.1883 - accuracy: 0.9273
Epoch 50/100
35/35 [==============================] - 0s 904us/step - loss: 0.1942 - accuracy: 0.9280
Epoch 51/100
35/35 [==============================] - 0s 907us/step - loss: 0.2016 - accuracy: 0.9245
Epoch 52/100
35/35 [==============================] - 0s 918us/step - loss: 0.2153 - accuracy: 0.9184
Epoch 53/100
35/35 [==============================] - 0s 940us/step - loss: 0.1989 - accuracy: 0.9251
Epoch 54/100
35/35 [==============================] - 0s 810us/step - loss: 0.2301 - accuracy: 0.9111
Epoch 55/100
35/35 [==============================] - 0s 843us/step - loss: 0.2158 - accuracy: 0.9154
Epoch 56/100
35/35 [==============================] - 0s 861us/step - loss: 0.2076 - accuracy: 0.9181
Epoch 57/100
35/35 [==============================] - 0s 922us/step - loss: 0.2004 - accuracy: 0.9345
Epoch 58/100
 1/35 [..............................] - ETA: 0s - loss: 0.2551 - accuracy: 0.9062
Epoch 00058: saving model to checkpoints/weights.58.hdf5
35/35 [==============================] - 0s 1ms/step - loss: 0.2185 - accuracy: 0.9187
Epoch 59/100
35/35 [==============================] - 0s 892us/step - loss: 0.2217 - accuracy: 0.9093
Epoch 60/100
35/35 [==============================] - 0s 826us/step - loss: 0.2024 - accuracy: 0.9250
Epoch 61/100
35/35 [==============================] - 0s 936us/step - loss: 0.2098 - accuracy: 0.9175
Epoch 62/100
35/35 [==============================] - 0s 844us/step - loss: 0.2058 - accuracy: 0.9194
Epoch 63/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1981 - accuracy: 0.9221
Epoch 64/100
35/35 [==============================] - 0s 924us/step - loss: 0.1791 - accuracy: 0.9315
Epoch 65/100
35/35 [==============================] - 0s 910us/step - loss: 0.1835 - accuracy: 0.9368
Epoch 66/100
35/35 [==============================] - 0s 943us/step - loss: 0.2176 - accuracy: 0.9145
Epoch 67/100
35/35 [==============================] - 0s 878us/step - loss: 0.1935 - accuracy: 0.9286
Epoch 68/100
35/35 [==============================] - 0s 988us/step - loss: 0.1791 - accuracy: 0.9353
Epoch 69/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1831 - accuracy: 0.9355
Epoch 70/100
35/35 [==============================] - 0s 859us/step - loss: 0.1810 - accuracy: 0.9295
Epoch 71/100
35/35 [==============================] - 0s 849us/step - loss: 0.1771 - accuracy: 0.9356
Epoch 72/100
35/35 [==============================] - 0s 930us/step - loss: 0.1745 - accuracy: 0.9292
Epoch 73/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2067 - accuracy: 0.9263
Epoch 74/100
35/35 [==============================] - 0s 817us/step - loss: 0.1658 - accuracy: 0.9304
Epoch 75/100
35/35 [==============================] - 0s 806us/step - loss: 0.1764 - accuracy: 0.9318
Epoch 76/100
35/35 [==============================] - 0s 877us/step - loss: 0.1762 - accuracy: 0.9277
Epoch 77/100
35/35 [==============================] - 0s 837us/step - loss: 0.1716 - accuracy: 0.9391
Epoch 78/100

35/35 [==============================] - 0s 857us/step - loss: 0.1620 - accuracy: 0.9349
Epoch 79/100
35/35 [==============================] - 0s 864us/step - loss: 0.1587 - accuracy: 0.9458
Epoch 80/100
35/35 [==============================] - 0s 801us/step - loss: 0.1557 - accuracy: 0.9422
Epoch 81/100
35/35 [==============================] - 0s 812us/step - loss: 0.1692 - accuracy: 0.9401
Epoch 82/100
35/35 [==============================] - 0s 844us/step - loss: 0.1759 - accuracy: 0.9164
Epoch 83/100
35/35 [==============================] - 0s 816us/step - loss: 0.1829 - accuracy: 0.9270
Epoch 84/100
35/35 [==============================] - 0s 793us/step - loss: 0.1727 - accuracy: 0.9362
Epoch 85/100
35/35 [==============================] - 0s 831us/step - loss: 0.1576 - accuracy: 0.9355
Epoch 86/100
 1/35 [..............................] - ETA: 0s - loss: 0.2033 - accuracy: 0.9375
Epoch 00086: saving model to checkpoints/weights.86.hdf5
35/35 [==============================] - 0s 1ms/step - loss: 0.1686 - accuracy: 0.9309
Epoch 87/100
35/35 [==============================] - 0s 913us/step - loss: 0.1564 - accuracy: 0.9401
Epoch 88/100
35/35 [==============================] - 0s 980us/step - loss: 0.1431 - accuracy: 0.9412
Epoch 89/100
35/35 [==============================] - 0s 848us/step - loss: 0.1573 - accuracy: 0.9473
Epoch 90/100
35/35 [==============================] - 0s 889us/step - loss: 0.1550 - accuracy: 0.9414
Epoch 91/100
35/35 [==============================] - 0s 881us/step - loss: 0.1557 - accuracy: 0.9245
Epoch 92/100
35/35 [==============================] - 0s 883us/step - loss: 0.1489 - accuracy: 0.9491
Epoch 93/100
35/35 [==============================] - 0s 874us/step - loss: 0.1253 - accuracy: 0.9518
Epoch 94/100
35/35 [==============================] - 0s 896us/step - loss: 0.1501 - accuracy: 0.9418
Epoch 95/100
35/35 [==============================] - 0s 871us/step - loss: 0.1404 - accuracy: 0.9511
Epoch 96/100
35/35 [==============================] - 0s 839us/step - loss: 0.1570 - accuracy: 0.9416
Epoch 97/100
35/35 [==============================] - 0s 824us/step - loss: 0.1416 - accuracy: 0.9402
Epoch 98/100
35/35 [==============================] - 0s 854us/step - loss: 0.1540 - accuracy: 0.9406
Epoch 99/100
35/35 [==============================] - 0s 809us/step - loss: 0.1294 - accuracy: 0.9525
Epoch 100/100
35/35 [==============================] - 0s 844us/step - loss: 0.1488 - accuracy: 0.9518
12/12 - 0s - loss: 0.4470 - accuracy: 0.8614
Loss: 0.4470062553882599, Accuracy: 0.8614130616188049

In [13]:
# Define the model - deep neural net
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  8
hidden_nodes_layer2 = 5

nn_new = tf.keras.models.Sequential()

# First hidden layer
nn_new.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn_new.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn_new.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the model
nn_new.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Restore the model weights
nn_new.load_weights("checkpoints/weights.86.hdf5")

# Evaluate the model using the test data
model_loss, model_accuracy = nn_new.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

12/12 - 0s - loss: 0.4168 - accuracy: 0.8587
Loss: 0.4167543947696686, Accuracy: 0.8586956262588501

In [14]:
# Export our model to HDF5 file
nn_new.save("trained_attrition.h5")